### ISSUE TITLE
chaining interceptors broken on error response

### ISSUE THREAD

**Issue by migajek** [aurelia/http-client#100]
Returing the error response from first "responseError" interceptor causes the "response" method on the second one to be fired 

I believe this is wrong, because the response returned from first interceptor is still the error response.

Here's the code

```ts
class Interceptor1 {
    responseError(error) {
        console.debug("1 error: ", error);
        return error;
    }
    response(response) {
        console.debug("1 ok: ", response);
        return response;
    }
}

class Interceptor2 {
    responseError(error) {
        console.debug("2 error: ", error);
        return error;
    }
    response(response) {
        console.debug("2 ok: ", response);
        return response;
    }
}


this.http
            .configure((x) => x.withInterceptor(new Interceptor2))
            .configure((x) => x.withInterceptor(new Interceptor1))
```

the error response causes the following console output

```
1. error
2. ok
```

I believe it should be 
```
1. error
2. error
```

**Comment by bryanrsmith** [comment]
This is by design. `response` and `responseError` act as the fulfillment and rejection callbacks to a `Promise`. This lets `responseError` recover from the error if desired. If you'd like the error to propagate to downstream handlers you'll need to either `throw error;` or `return Promise.reject(error);`
