### ISSUE TITLE
Cancelling HTTP request does not reject promise

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/http-client#115]
Calling `cancel()` or `abort()` on a request created by the httpClient does not reject any promises chained to that request. This means that, upon aborting a request, we're forced to handle errors in our success functions.

Is this by design? I think it would be easier to reject the promise upon request cancellation. In fact, there seems to be a property called "isAborted" in the processor and client that isn't actually used.

The reason I'm using the HttpClient over the fetch client right now is that this library supports XHR cancellation. If this has changed, I can switch, but I'm guessing that since the designs are similar this issue would apply to that library as well.

**Comment by bryanrsmith** [comment]
Definitely not by design. It looks like there's a test for it: https://github.com/aurelia/http-client/blob/master/test/request-message-processor.spec.js#L163
 Do you have an interceptor that might be recovering from response failures? A requestError interceptor needs to rethrow the error to propagate the failure.

Otherwise, is this something you'd be willing to look into? We're not putting much work into this library any more, but I'd be happy to merge a PR :-)

**Comment by jedd-ahyoung** [comment]
D'oh! That was it. I think that my requestError interceptor was left over from when I was testing the fetch-client for my project. I completely forgot that it's necessary to rethrow the exception. I guess everyone has their blind spots. :-P

This can be closed. My bad. Thanks!

**Comment by bryanrsmith** [comment]
No problem!
