### ISSUE TITLE
json object in get request faild to get to server.

### ISSUE THREAD

**Issue by eliavmaman** [aurelia/http-client#143]
I'm trying to send json object to the server.

my code 
 ```
getFullHistoryData(criteria) {
        return this.http.createRequest('api/getfullhistory').asGet().withParams({
            filterCriteria: {
                Financial: false,
                Login:true
            } }).send();
    }
```

the filter criteria in server is  a class with  Financial and Login properties.
the filterCriteria in the server is null.
do i need to declare that i m sending json?

**Comment by EisenbergEffect** [comment]
I think there's probably a mismatch in terms of what your server is expecting and what the client is sending. Since this is a GET request and you are using `withParams` its converting the object to query string parameters. I suspect the format doesn't match your server. Check what is going over the wire and make some adjustments.
