### ISSUE TITLE
Throttle Bandwidth

### ISSUE THREAD

**Issue by MMJM** [aurelia/http-client#145]
Hi,

I'm developing an Electron App using Aurelia that deals with the Upload and Download of files. I want this local web server to throttle its bandwidth usage as it will run in the background. I was going to use Aurelia's http-client library but I can't see any options to throttle network bandwidth. I've looked at NPM packages such as throttle and throttle-proxy which might help. 

Can anyone tell me if this is possible in http-client or of any NPM packages out there that would achieve what I'm after?

Alternatively, if someone thinks this could be added easily to Aurelia's http-client I might be prepared to have a go myself and submit a PR for it.

**Comment by EisenbergEffect** [comment]
Please ask questions on SO or Gitter rather than here. We use Github to track bugs and feature requests.

I haven't tried to accomplish specifically what you are asking, so I can't provide any further insight into how best to do that or whether it could be accomplished with our http-client (which just uses XmlHttpRequest or Fetch).

**Comment by MMJM** [comment]
I had tried Gitter but not got far with it.

Could this be a feature request?
