### ISSUE TITLE
Unable to change Content-Type header

### ISSUE THREAD

**Issue by miu-zsolt** [aurelia/http-client#16]
I would like to override Content-Type header when using this.http.put() and post.
The default content type is `"text/plain;charset=UTF-8"` but I need `"application/json"`.
I tried to attach `.withHeaders({ "Content-Type": "application/json" })` to put method, but it didn't work. 
Please provide a way to set this header. Thanks!

**Comment by EisenbergEffect** [comment]
It's a bit of a pain with the current release...but there's a new release coming today or tomorrow morning. With that version it's really easy. You can configure headers to be used by all requests, or per-request.

Here's is a header that will be used for every request:

```javascript
var client = new HttpClient()
  .configure(x => {
    x.withBaseUrl(baseUrl);
    x.withHeader('Authorization', 'bearer 123');
  });

client.get('some/cool/path');
```

The configure API will let you set up options to be used on all requests. The same API is available per-request though. So, instead of calling `get` first, you can do this:

```javascript
var client = new HttpClient()
  .configure(x => {
    x.withBaseUrl(baseUrl);
  });

client.request
  .withHeader('Authorization', 'bearer 123')
  .get('some/cool/path');
```

So, in this case the `baseUrl` will be used for all requests, but the header will only be used for the one invoked get request.

Hope that makes sense. This is part of a major overhaul to the http client. It's releasing today or tomorrow.

**Comment by miu-zsolt** [comment]
Thank you, it totally makes sense for me. I'm looking for the new release ;)

**Comment by ghiotion** [comment]
Ditto.  And can I tell you how much I'm loving Aurelia?  I've been playing with it extensively for the past 48 hours and it's just flat out fantastic.

**Comment by EisenbergEffect** [comment]
Awesome! We still have a lot of work to do but I'm encouraged by the community response. If you can stick around while we work out the kinks....I think we're going to have something really nice.

**Comment by yale** [comment]
Hi! I'm not able to set a header on 0.5.2, neither by using the configure function nor the withHeader function:

```es6
import {HttpClient} from 'aurelia-http-client';

export class Spacemoney{
  static inject() { return [HttpClient]; }

  constructor(http) {
    this.env = 'development';
    this.apiToken = '...';
    this.http = http.request.withHeader('Authorization', 'Token token="' + this.apiToken + '"');
  }
  ...
}
```

When the request is made, no Authorization header is set. Let me know if there's any more information I can provide that would help.

BTW, I have been building a sideproject using Aurelia for the past 72 hours, and I am in love. I'm so excited to see this project mature!

**Comment by EisenbergEffect** [comment]
We have unit tests that do just this, so that's a little baffling. Is it possible for you to write a test case for us that fails?

**Comment by PeterWone** [comment]
This code (in app.ts before the app class just while I figure it out)

```
import {HttpClient} from 'aurelia-http-client';

let client = new HttpClient();
let req = client.createRequest("http://test.assaohs.net/DAL3/api/Form")
 .asPost()
 .withHeader("Content-Type", "application/json; charset=UTF-8")
 .withContent('{ "UID" : "18974", "Command" : "get", "Raw" : null }')
 .send()
 .then(res=>{
   console.log(res.response);
 });

```

When the withHeader clause is absent, the request has content type text/plain and fails as a result of that.

When the withHeader clause is present, the request has no content type at all because it transmutes into OPTIONS due to the call being cross site, and fails as a result of that being an unsupported verb at the server, which _is configured to allow the call._

Preflighting is required for cross site requests with _non-standard_ headers. Content-Type is hardly a non-standard header so this is incorrect behaviour.
