### ISSUE TITLE
http.setRequestsHeader

### ISSUE THREAD

**Issue by ghiotion** [aurelia/http-client#17]
I'm trying to post JSON to my api endpoint.  If I make an XMLHttpRequest() it works.  If I make an http-client, it doesn't.  

        var data = {"image": "http://placekitten.com/200/200/?image=9", "title": "test"};
        
        //this works... 
        var xmlhttp = new XMLHttpRequest();   
        xmlhttp.open("POST", "/api/pin");
        xmlhttp.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        xmlhttp.send(JSON.stringify(data));        

        //this does not - just causes the page to browsersync to refresh the page
        this.http.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        this.http.post('/api/pin', JSON.stringify(data));

**Comment by EisenbergEffect** [comment]
There is no `setRequestHeader` api on http-client.

**Comment by ghiotion** [comment]
Thanks for the response.  If not, what is the correct way to set the response header for JSON post data?  I just saw issue #16.  What's the correct way to post JSON data with the http.post method?

**Comment by EisenbergEffect** [comment]
It's a bit of a pain with the current release...but there's a new release coming today or tomorrow morning. With that version it's really easy. You can configure headers to be used by all requests, or per-request.

Here's is a header that will be used for every request:

```javascript
var client = new HttpClient()
  .configure(x => {
    x.withBaseUrl(baseUrl);
    x.withHeader('Authorization', 'bearer 123');
  });

client.get('some/cool/path');
```

The configure API will let you set up options to be used on all requests. The same API is available per-request though. So, instead of calling `get` first, you can do this:

```javascript
var client = new HttpClient()
  .configure(x => {
    x.withBaseUrl(baseUrl);
  });

client.request
  .withHeader('Authorization', 'bearer 123')
  .get('some/cool/path');
```

So, in this case the `baseUrl` will be used for all requests, but the header will only be used for the one invoked get request.

Hope that makes sense. This is part of a major overhaul to the http client. It's releasing today or tomorrow.
