### ISSUE TITLE
Consider dropping or using the fetch polyfill

### ISSUE THREAD

**Issue by lukeapage** [aurelia/http-client#59]
I like what I've seen of Aurelia, but I was surprised with such a forward focus that you still have a http module.

given the new fetch standard (implemented in chrome today, firefox very soon - http://caniuse.com/#feat=fetch) and fetch polyfill - https://github.com/github/fetch, would it be better to either abandon this part of Aurelia or if it does provide functionality over fetch (sorry, have only looked at the basic features) then base this on top of fetch instead of XmlHttpRequest ?

**Comment by EisenbergEffect** [comment]
We have looked into fetch and we were considering whether or not we should base our http library on it or if we should create a separate library. I haven't thought about it a little bit though. @bryanrsmith would you look into this and see what your recommendation would be? Is there a way to alter our HttpClient implementation without making a breaking change in the API? If not, could be build a fetch-based implementation that was similar and easy to migrate to, with the same features?

**Comment by bryanrsmith** [comment]
There are two significant features that aurelia-http-client provides that fetch doesn't directly support.

1. JSONP
2. Application-level management of requests. Interceptors, default configuration for things like base URL, centralized request tracking for global activity indicators, etc.

IMO, the fetch API is quite nice and well suited for direct use without a wrapping library. We certainly could integrate it here, but I don't think we'd stand to gain much. fetch already provides most of the same functionality, and it would be awkward to map some of fetch's more advanced features to this API.

I think we should aim for building a new library with a very thin wrapper around fetch. Just enough to let us inject the application-level stuff like interceptors, and maybe make testing a little easier. I think JSONP is different enough that we could tack on a little helper method adjacent to the fetch wrapper instead of abstracting it away. That would give us a lot less code to maintain, and help avoid breakages as the fetch API evolves.

**Comment by lukeapage** [comment]
Sounds good!

**Comment by EisenbergEffect** [comment]
We've got a new fetch plugin which you can not use in place of the http-client in you prefer :)

**Comment by bryanrsmith** [comment]
Link for convenience: https://github.com/aurelia/fetch-client. Docs coming :-)
