### ISSUE TITLE
How to pass object from httpclient request to interceptor?

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/http-client#61]
Practical case: 
- adding an authentication token happens inside request interceptor.
- I need a mechanism in order the exclude the token for certain request messages (the majority of request needs to include the token), so that particular request are enriched with {"skipToken": true}. The interceptor could then use skipToken in it's internal processing.

I don't see a straight-forward way to do this?
thanks.

**Comment by Mordred** [comment]
I think that you can add your own transformation to the RequestBuilder:

```js
import { RequestBuilder } from 'aurelia-http-client';

RequestBuilder.addHelper('noAuthToken', function(){
  return function(client, processor, message){
    message.noAuthToken = true;
  };
});
```

Then inside your interceptor:

```js
class AuthInterceptor {
  request(message) {
    if (!message.noAuthToken) {
      // Add auth token
    }
  }
}
```

**Comment by paulvanbladel** [comment]
Thanks a lot for the help. That works.
So, I did a addHelper inside my app.js activate method (is this the best place ?) and updated the interceptor.
and where I use the createRequest I do:
 activate(){
   return this.http.createRequest(this.url)
  .asGet()
  .noAuthToken()
  .send().then(response => {
      this.customers = response.content;
    });
  }

So, is HttpClient acting as kind of singleton here?
I am doing the addHelper in app.js and again injecting HttpClient in customer.js. So, the patch on HttpClient is known in customer.js.
Must be :)

**Comment by atsu85** [comment]
@paulvanbladel Can't you just add a custom transformer as i described here https://github.com/aurelia/http-client/issues/60 
and do simple 
`this.http.get(this.url)`
instead of creating custom helper and messing around with 
>```
this.http.createRequest(this.url)
.asGet()
.noAuthToken()
.send()
```

?

**Comment by pmarchio** [comment]
am struggling trying to implement this exact solution to skip token processing in Paul's excellent aurelia-auth plugin. Pretty sure the issue is around accessing the message at the appropriate time as I have added the transformation to request builder and 'noAuthToken' shows up true in chrome dev tools when I dump the message and drill down, but the value is undefined when I try to access it (too early I suspect?).  However, I do not have the code wrapped inside 'request(message)'.  Is this a real function, I can not seem to resolve it anywhere.

thanks in advance for any guidance :)
